import Link from 'next/link'
import Image from 'next/image'

export const metadata = {
  title: "Privacy Policy – Codeforge AI",
  description: "Codeforge AI privacy policy — your data never leaves your machine.",
}

export default function PrivacyPolicy() {
  return (
    <main className="min-h-screen bg-[#060d1a] text-white">

      {/* Nav */}
      <nav className="border-b border-white/5 bg-[#060d1a]/80 backdrop-blur-xl sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center gap-3">
          <Link href="/" className="flex items-center gap-2.5 hover:opacity-80 transition-opacity">
            <div className="w-7 h-7 rounded-lg overflow-hidden ring-1 ring-white/10">
              <Image src="/logo.png" alt="Codeforge AI" width={28} height={28} className="w-full h-full object-cover" />
            </div>
            <span className="font-bold text-sm">Codeforge <span className="text-cyan-400">AI</span></span>
          </Link>
          <span className="text-slate-600 text-sm">/</span>
          <span className="text-slate-400 text-sm">Privacy Policy</span>
        </div>
      </nav>

      <div className="max-w-3xl mx-auto px-6 py-16">

        {/* Header */}
        <div className="mb-12">
          <p className="text-[11px] font-bold text-cyan-400 tracking-[0.2em] uppercase mb-3">Legal</p>
          <h1 className="text-3xl md:text-4xl font-black text-white mb-3">Privacy Policy</h1>
          <p className="text-slate-400 text-sm">Last updated: January 2025</p>
        </div>

        {/* Highlight box */}
        <div className="mb-10 p-5 rounded-xl bg-cyan-500/5 border border-cyan-500/20">
          <p className="text-cyan-300 text-sm font-medium leading-relaxed">
            <span className="font-bold text-cyan-400">Short version:</span> Codeforge AI runs entirely on your device.
            Your documents, AI conversations, and data never leave your machine. We collect nothing.
          </p>
        </div>

        <div className="space-y-10 text-slate-300 text-sm leading-relaxed">

          <section>
            <h2 className="text-lg font-bold text-white mb-3 flex items-center gap-2">
              <span className="w-1.5 h-1.5 bg-cyan-400 rounded-full inline-block" />
              1. Overview
            </h2>
            <p>
              Codeforge AI is a desktop application that runs artificial intelligence models entirely on your local machine.
              This Privacy Policy explains how we handle information in connection with our website and software.
            </p>
            <p className="mt-3">
              Because Codeforge AI operates 100% offline, the vast majority of your activity — including all AI conversations,
              document uploads, and analysis — stays exclusively on your device and is never transmitted to any server,
              including ours.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3 flex items-center gap-2">
              <span className="w-1.5 h-1.5 bg-cyan-400 rounded-full inline-block" />
              2. What We Do NOT Collect
            </h2>
            <p className="mb-3">Codeforge AI does <strong className="text-white">not</strong> collect, store, or transmit any of the following:</p>
            <ul className="space-y-2 ml-4">
              {[
                'Your AI chat messages or conversation history',
                'Documents, PDFs, Word files, or Excel files you upload',
                'Code you paste or work with in the VS Code / Cursor extension',
                'Any output or responses generated by the AI',
                'Your file system, folder structure, or file names',
                'Keystrokes, screenshots, or usage recordings',
                'Personal identifiers such as name, email, or IP address (from the app)',
              ].map((item, i) => (
                <li key={i} className="flex items-start gap-2 text-slate-400">
                  <span className="text-cyan-400 mt-0.5 flex-shrink-0">✓</span>
                  {item}
                </li>
              ))}
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3 flex items-center gap-2">
              <span className="w-1.5 h-1.5 bg-cyan-400 rounded-full inline-block" />
              3. How the App Works (Offline by Design)
            </h2>
            <p>
              All AI processing in Codeforge AI runs locally using open-source language models (Qwen, Phi-3.5, Gemma 2)
              stored on your device. When you ask a question or analyze a document:
            </p>
            <ul className="mt-3 space-y-2 ml-4">
              {[
                'Your input is processed entirely on your CPU/GPU',
                'No request is made to any external AI API or server',
                'The AI response is generated on your machine and displayed locally',
                'Nothing is cached, logged, or stored outside your device',
              ].map((item, i) => (
                <li key={i} className="flex items-start gap-2 text-slate-400">
                  <span className="text-blue-400 mt-0.5 flex-shrink-0">→</span>
                  {item}
                </li>
              ))}
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3 flex items-center gap-2">
              <span className="w-1.5 h-1.5 bg-cyan-400 rounded-full inline-block" />
              4. Model Downloads
            </h2>
            <p>
              When you choose to download an AI model inside the app, the file is fetched directly from
              HuggingFace.co (a public model hosting platform) to your local device. This download is initiated
              by you and is subject to HuggingFace&apos;s own privacy policy. Codeforge AI does not intercept,
              log, or store any information related to this download.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3 flex items-center gap-2">
              <span className="w-1.5 h-1.5 bg-cyan-400 rounded-full inline-block" />
              5. VS Code / Cursor Extension
            </h2>
            <p>
              The Codeforge AI VS Code extension communicates exclusively with your local Codeforge AI desktop app
              via a WebSocket connection on <code className="text-cyan-400 bg-cyan-500/10 px-1.5 py-0.5 rounded text-xs">ws://127.0.0.1:7471</code> — a loopback address on your own machine.
              No code, file content, or editor context is sent to any external server. The connection never leaves your device.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3 flex items-center gap-2">
              <span className="w-1.5 h-1.5 bg-cyan-400 rounded-full inline-block" />
              6. Website Contact Form
            </h2>
            <p>
              Our website includes an optional contact form powered by Formspree. If you choose to submit it,
              the information you provide (name, email address, and message) is sent to Formspree and forwarded
              to us. We use this solely to respond to your enquiry. We do not add you to mailing lists or share
              your details with third parties. Formspree&apos;s own privacy policy applies to data processed through their service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3 flex items-center gap-2">
              <span className="w-1.5 h-1.5 bg-cyan-400 rounded-full inline-block" />
              7. Website Analytics &amp; Cookies
            </h2>
            <p>
              Our website does not use advertising cookies or cross-site tracking. We may use minimal,
              privacy-respecting analytics to understand general traffic patterns (e.g., page views).
              No personally identifiable information is collected via analytics.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3 flex items-center gap-2">
              <span className="w-1.5 h-1.5 bg-cyan-400 rounded-full inline-block" />
              8. Children&apos;s Privacy
            </h2>
            <p>
              Codeforge AI is not directed at children under the age of 13. We do not knowingly collect
              any personal information from children. If you believe a child has submitted information
              through our contact form, please contact us and we will delete it promptly.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3 flex items-center gap-2">
              <span className="w-1.5 h-1.5 bg-cyan-400 rounded-full inline-block" />
              9. Changes to This Policy
            </h2>
            <p>
              We may update this Privacy Policy from time to time. Any changes will be reflected on this page
              with an updated date. Continued use of the software or website after changes constitutes your
              acceptance of the revised policy.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3 flex items-center gap-2">
              <span className="w-1.5 h-1.5 bg-cyan-400 rounded-full inline-block" />
              10. Contact Us
            </h2>
            <p>
              If you have any questions or concerns about this Privacy Policy, please reach out:
            </p>
            <div className="mt-3 p-4 rounded-xl bg-white/3 border border-white/8 inline-block">
              <p className="text-white font-medium">Codeforge AI</p>
              <a href="mailto:codeforeai.app@gmail.com" className="text-cyan-400 hover:text-cyan-300 transition-colors">
                codeforeai.app@gmail.com
              </a>
            </div>
          </section>

        </div>

        {/* Back link */}
        <div className="mt-14 pt-8 border-t border-white/5">
          <Link href="/" className="text-cyan-400 hover:text-cyan-300 text-sm transition-colors flex items-center gap-2">
            ← Back to Codeforge AI
          </Link>
        </div>
      </div>
    </main>
  )
}
